// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://vznsrjdjrukijudqpcgy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ6bnNyamRqcnVraWp1ZHFwY2d5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQ3NTk3ODQsImV4cCI6MjA4MDMzNTc4NH0.Kg5MJgmz0B2aUfkY8tV_qj9EeGlumZBWDEpn87qFfSo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);